/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrescriptionsRouteImport } from './routes/prescriptions'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as MedicinesRouteImport } from './routes/medicines'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QueueIndexRouteImport } from './routes/queue.index'
import { Route as ConsultationIndexRouteImport } from './routes/consultation.index'
import { Route as QueueQueueIdRouteImport } from './routes/queue.$queueId'
import { Route as ConsultationQueueIdRouteImport } from './routes/consultation.$queueId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsRoute = PrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicinesRoute = MedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueIndexRoute = QueueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QueueRoute,
} as any)
const ConsultationIndexRoute = ConsultationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsultationRoute,
} as any)
const QueueQueueIdRoute = QueueQueueIdRouteImport.update({
  id: '/$queueId',
  path: '/$queueId',
  getParentRoute: () => QueueRoute,
} as any)
const ConsultationQueueIdRoute = ConsultationQueueIdRouteImport.update({
  id: '/$queueId',
  path: '/$queueId',
  getParentRoute: () => ConsultationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/consultation': typeof ConsultationRouteWithChildren
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/medicines': typeof MedicinesRoute
  '/patients': typeof PatientsRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/profile': typeof ProfileRoute
  '/queue': typeof QueueRouteWithChildren
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/consultation/$queueId': typeof ConsultationQueueIdRoute
  '/queue/$queueId': typeof QueueQueueIdRoute
  '/consultation/': typeof ConsultationIndexRoute
  '/queue/': typeof QueueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/medicines': typeof MedicinesRoute
  '/patients': typeof PatientsRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/consultation/$queueId': typeof ConsultationQueueIdRoute
  '/queue/$queueId': typeof QueueQueueIdRoute
  '/consultation': typeof ConsultationIndexRoute
  '/queue': typeof QueueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/consultation': typeof ConsultationRouteWithChildren
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/medicines': typeof MedicinesRoute
  '/patients': typeof PatientsRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/profile': typeof ProfileRoute
  '/queue': typeof QueueRouteWithChildren
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/consultation/$queueId': typeof ConsultationQueueIdRoute
  '/queue/$queueId': typeof QueueQueueIdRoute
  '/consultation/': typeof ConsultationIndexRoute
  '/queue/': typeof QueueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/consultation'
    | '/doctors'
    | '/login'
    | '/medicines'
    | '/patients'
    | '/prescriptions'
    | '/profile'
    | '/queue'
    | '/settings'
    | '/users'
    | '/consultation/$queueId'
    | '/queue/$queueId'
    | '/consultation/'
    | '/queue/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/doctors'
    | '/login'
    | '/medicines'
    | '/patients'
    | '/prescriptions'
    | '/profile'
    | '/settings'
    | '/users'
    | '/consultation/$queueId'
    | '/queue/$queueId'
    | '/consultation'
    | '/queue'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/consultation'
    | '/doctors'
    | '/login'
    | '/medicines'
    | '/patients'
    | '/prescriptions'
    | '/profile'
    | '/queue'
    | '/settings'
    | '/users'
    | '/consultation/$queueId'
    | '/queue/$queueId'
    | '/consultation/'
    | '/queue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  ConsultationRoute: typeof ConsultationRouteWithChildren
  DoctorsRoute: typeof DoctorsRoute
  LoginRoute: typeof LoginRoute
  MedicinesRoute: typeof MedicinesRoute
  PatientsRoute: typeof PatientsRoute
  PrescriptionsRoute: typeof PrescriptionsRoute
  ProfileRoute: typeof ProfileRoute
  QueueRoute: typeof QueueRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions': {
      id: '/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof PrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicines': {
      id: '/medicines'
      path: '/medicines'
      fullPath: '/medicines'
      preLoaderRoute: typeof MedicinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/': {
      id: '/queue/'
      path: '/'
      fullPath: '/queue/'
      preLoaderRoute: typeof QueueIndexRouteImport
      parentRoute: typeof QueueRoute
    }
    '/consultation/': {
      id: '/consultation/'
      path: '/'
      fullPath: '/consultation/'
      preLoaderRoute: typeof ConsultationIndexRouteImport
      parentRoute: typeof ConsultationRoute
    }
    '/queue/$queueId': {
      id: '/queue/$queueId'
      path: '/$queueId'
      fullPath: '/queue/$queueId'
      preLoaderRoute: typeof QueueQueueIdRouteImport
      parentRoute: typeof QueueRoute
    }
    '/consultation/$queueId': {
      id: '/consultation/$queueId'
      path: '/$queueId'
      fullPath: '/consultation/$queueId'
      preLoaderRoute: typeof ConsultationQueueIdRouteImport
      parentRoute: typeof ConsultationRoute
    }
  }
}

interface ConsultationRouteChildren {
  ConsultationQueueIdRoute: typeof ConsultationQueueIdRoute
  ConsultationIndexRoute: typeof ConsultationIndexRoute
}

const ConsultationRouteChildren: ConsultationRouteChildren = {
  ConsultationQueueIdRoute: ConsultationQueueIdRoute,
  ConsultationIndexRoute: ConsultationIndexRoute,
}

const ConsultationRouteWithChildren = ConsultationRoute._addFileChildren(
  ConsultationRouteChildren,
)

interface QueueRouteChildren {
  QueueQueueIdRoute: typeof QueueQueueIdRoute
  QueueIndexRoute: typeof QueueIndexRoute
}

const QueueRouteChildren: QueueRouteChildren = {
  QueueQueueIdRoute: QueueQueueIdRoute,
  QueueIndexRoute: QueueIndexRoute,
}

const QueueRouteWithChildren = QueueRoute._addFileChildren(QueueRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  ConsultationRoute: ConsultationRouteWithChildren,
  DoctorsRoute: DoctorsRoute,
  LoginRoute: LoginRoute,
  MedicinesRoute: MedicinesRoute,
  PatientsRoute: PatientsRoute,
  PrescriptionsRoute: PrescriptionsRoute,
  ProfileRoute: ProfileRoute,
  QueueRoute: QueueRouteWithChildren,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
