import {
  Activity,
  ArrowLeft,
  ArrowRight,
  ChevronDown,
  ChevronUp,
  CalendarDays,
  LayoutDashboard,
  RefreshCcw,
  Clock3,
  Bell,
  CalendarClock,
  ClipboardList,
  Stethoscope,
  FlaskConical,
  Pill,
  Printer,
  Settings,
  ShieldPlus,
  Check,
  Play,
  House,
  LockKeyhole,
  Mail,
  Mars,
  Menu,
  Plus,
  Search,
  Sparkles,
  UserRound,
  UserPlus,
  Venus,
  Zap,
  X,
  CircleEllipsis,
  Ellipsis,
  EllipsisVertical,
  Heart,
  Thermometer,
  Gauge,
  Weight,
  Users,
  type LucideIcon,
  Table2,
  List,
  SquarePen,
  Trash2
} from "lucide-react";

export const iconMap = {
  activity: Activity,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  calendarDays: CalendarDays,
  layoutDashboard: LayoutDashboard,
  refreshCcw: RefreshCcw,
  clock3: Clock3,
  bell: Bell,
  calendarClock: CalendarClock,
  clipboardList: ClipboardList,
  stethoscope: Stethoscope,
  flaskConical: FlaskConical,
  pill: Pill,
  printer: Printer,
  settings: Settings,
  shieldPlus: ShieldPlus,
  check: Check,
  play: Play,
  home: House,
  lock: LockKeyhole,
  mail: Mail,
  mars: Mars,
  menu: Menu,
  plus: Plus,
  search: Search,
  sparkles: Sparkles,
  user: UserRound,
  userPlus: UserPlus,
  venus: Venus,
  zap: Zap,
  x: X,
  circleEllipsis: CircleEllipsis,
  ellipsis: Ellipsis,
  ellipsisVertical: EllipsisVertical,
  heart: Heart,
  thermometer: Thermometer,
  gauge: Gauge,
  weight: Weight,
  users: Users,
  "table-2": Table2,
  list: List,
  squarePen: SquarePen,
  trash2: Trash2
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;
